PLANTILLAS = {
    "GT - DT - MAÍZ": [
        {"Producto": "Tortrix 17G",           "Fabricante": "PEPSICO",  "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 17, "SOM (%)": 13.68},
        {"Producto": "Tortrix 38G",           "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 1.98, "Gramaje (g)": 38, "SOM (%)": 7.02},
        {"Producto": "Tortrix 35G",           "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 1.98, "Gramaje (g)": 35, "SOM (%)": 5.31},
        {"Producto": "Tortrix 33G",           "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 1.98, "Gramaje (g)": 33, "SOM (%)": 10.75},
        {"Producto": "Tortrix 32G",           "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 1.98, "Gramaje (g)": 32, "SOM (%)": 2.31},
        {"Producto": "Doritos 25G",           "Fabricante": "PEPSICO",  "Ocasión": "BITES",      "Precio ($)": 1.98, "Gramaje (g)": 25, "SOM (%)": 3.36},
        {"Producto": "Doritos 33G",           "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 2.52, "Gramaje (g)": 33, "SOM (%)": 0.20},
        {"Producto": "Doritos 48G",           "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 4.04, "Gramaje (g)": 48, "SOM (%)": 9.02},
        {"Producto": "Taqueritos 34G",        "Fabricante": "YUMMIES",  "Ocasión": "INDIVIDUAL", "Precio ($)": 1.98, "Gramaje (g)": 34, "SOM (%)": 10.42},
        {"Producto": "Diana Jalapeño 17G",    "Fabricante": "DIANA",    "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 17, "SOM (%)": 4.77},
        {"Producto": "Diana Jalapeño 39G",    "Fabricante": "DIANA",    "Ocasión": "INDIVIDUAL", "Precio ($)": 1.98, "Gramaje (g)": 39, "SOM (%)": 1.48},
        {"Producto": "Diana Nachos 17G",      "Fabricante": "DIANA",    "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 17, "SOM (%)": 4.86},
        {"Producto": "Takis 28G",             "Fabricante": "BARCEL",   "Ocasión": "BITES",      "Precio ($)": 2.98, "Gramaje (g)": 28, "SOM (%)": 0.09},
        {"Producto": "Takis 49G",             "Fabricante": "BARCEL",   "Ocasión": "INDIVIDUAL", "Precio ($)": 5.34, "Gramaje (g)": 49, "SOM (%)": 4.39},
        {"Producto": "Ranchitas 17G",         "Fabricante": "YUMMIES",  "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 17, "SOM (%)": 4.24},
        {"Producto": "Rancheritos 19G",       "Fabricante": "PEPSICO",  "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 19, "SOM (%)": 1.75},
    ],

    "GT - DT - PAPA": [
        {"Producto": "Lay's 18G",             "Fabricante": "PEPSICO",  "Ocasión": "BITES",      "Precio ($)": 2.52,  "Gramaje (g)": 18, "SOM (%)": 17.99},
        {"Producto": "Lay's 28G",             "Fabricante": "PEPSICO",  "Ocasión": "BITES",      "Precio ($)": 4.04,  "Gramaje (g)": 28, "SOM (%)": 3.27},
        {"Producto": "Pringles 21G",          "Fabricante": "KELLOGGS", "Ocasión": "BITES",      "Precio ($)": 5.04,  "Gramaje (g)": 21, "SOM (%)": 3.08},
        {"Producto": "Pringles 19G",          "Fabricante": "KELLOGGS", "Ocasión": "BITES",      "Precio ($)": 5.19,  "Gramaje (g)": 19, "SOM (%)": 1.12},
        {"Producto": "Zibas 26G",             "Fabricante": "DINANT",   "Ocasión": "BITES",      "Precio ($)": 2.98,  "Gramaje (g)": 26, "SOM (%)": 4.61},
        {"Producto": "Zibas 18G",             "Fabricante": "DINANT",   "Ocasión": "BITES",      "Precio ($)": 1.37,  "Gramaje (g)": 18, "SOM (%)": 3.24},
        {"Producto": "Lay's 31G",             "Fabricante": "PEPSICO",  "Ocasión": "INDIVIDUAL", "Precio ($)": 4.04,  "Gramaje (g)": 31, "SOM (%)": 34.77},
        {"Producto": "Chip's 36G",            "Fabricante": "BARCEL",   "Ocasión": "INDIVIDUAL", "Precio ($)": 5.34,  "Gramaje (g)": 36, "SOM (%)": 14.36},
        {"Producto": "Pringles 37G",          "Fabricante": "KELLOGGS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.15, "Gramaje (g)": 37, "SOM (%)": 1.30},
    ],

    "GT - DT - EXTRUIDO": [
        {"Producto": "Cebollitas 11G",        "Fabricante": "PEPSICO",      "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 11, "SOM (%)": 6.62},
        {"Producto": "Pikarones 11G",         "Fabricante": "PEPSICO",      "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 11, "SOM (%)": 6.41},
        {"Producto": "Diana Churritos 12G",   "Fabricante": "DIANA",        "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 12, "SOM (%)": 4.77},
        {"Producto": "Dobrecitos 12G",        "Fabricante": "BOCADELI",     "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 12, "SOM (%)": 4.43},
        {"Producto": "Diana Centavitos 12G",  "Fabricante": "DIANA",        "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 12, "SOM (%)": 3.28},
        {"Producto": "Diana Quesitos 13G",    "Fabricante": "DIANA",        "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 13, "SOM (%)": 5.58},
        {"Producto": "Quesitrix 13G",         "Fabricante": "BOCADELI",     "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 13, "SOM (%)": 1.85},
        {"Producto": "Cappy 14G",             "Fabricante": "DINANT",       "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 14, "SOM (%)": 3.41},
        {"Producto": "Cappy 16G",             "Fabricante": "DINANT",       "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 16, "SOM (%)": 1.29},
        {"Producto": "Dobrecitos 16G",        "Fabricante": "BOCADELI",     "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 16, "SOM (%)": 0.24},
        {"Producto": "Tortillitas 20G",       "Fabricante": "SEÑORIAL",     "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 20, "SOM (%)": 8.81},
        {"Producto": "Cappy 20G",             "Fabricante": "DINANT",       "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 20, "SOM (%)": 2.25},
        {"Producto": "Quesifritos 20G",       "Fabricante": "ALIMENTOS SA", "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 20, "SOM (%)": 5.90},
        {"Producto": "Cheetos 17G",           "Fabricante": "PEPSICO",      "Ocasión": "BITES",      "Precio ($)": 1.91, "Gramaje (g)": 17, "SOM (%)": 9.74},
        {"Producto": "Crujitos 17G",          "Fabricante": "PEPSICO",      "Ocasión": "BITES",      "Precio ($)": 1.98, "Gramaje (g)": 17, "SOM (%)": 1.85},
        {"Producto": "Cheetos 21G",           "Fabricante": "PEPSICO",      "Ocasión": "BITES",      "Precio ($)": 1.98, "Gramaje (g)": 21, "SOM (%)": 2.08},
        {"Producto": "Cheetos 29G",           "Fabricante": "PEPSICO",      "Ocasión": "INDIVIDUAL", "Precio ($)": 3.59, "Gramaje (g)": 29, "SOM (%)": 6.10},
    ],

    "GT - DT - MIXES": [
        {"Producto": "Tortrix 30G",           "Fabricante": "PEPSICO",      "Ocasión": "BITES",      "Precio ($)": 2.06, "Gramaje (g)": 30, "SOM (%)": 9.78},
        {"Producto": "Tortrix 39G",           "Fabricante": "PEPSICO",      "Ocasión": "INDIVIDUAL", "Precio ($)": 2.44, "Gramaje (g)": 39, "SOM (%)": 3.32},
        {"Producto": "Tortrix 45G",           "Fabricante": "PEPSICO",      "Ocasión": "INDIVIDUAL", "Precio ($)": 2.52, "Gramaje (g)": 45, "SOM (%)": 26.82},
        {"Producto": "De Todito 48G",         "Fabricante": "PEPSICO",      "Ocasión": "INDIVIDUAL", "Precio ($)": 5.11, "Gramaje (g)": 20, "SOM (%)": 20.43},  # ⚠️ Gramos=20 en tu fuente, revisar
        {"Producto": "De Todito 55G",         "Fabricante": "PEPSICO",      "Ocasión": "INDIVIDUAL", "Precio ($)": 5.04, "Gramaje (g)": 55, "SOM (%)": 9.54},
        {"Producto": "Tortrillitas Mix 20G",  "Fabricante": "ALIMENTOS SA", "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 20, "SOM (%)": 15.42},
        {"Producto": "Tortrillitas Mix 16G",  "Fabricante": "ALIMENTOS SA", "Ocasión": "BITES",      "Precio ($)": 0.99, "Gramaje (g)": 16, "SOM (%)": 3.75},
        {"Producto": "Tortrillitas Mix 50G",  "Fabricante": "ALIMENTOS SA", "Ocasión": "INDIVIDUAL", "Precio ($)": 2.06, "Gramaje (g)": 50, "SOM (%)": 0.53},
        {"Producto": "Big Mix 40G",           "Fabricante": "BARCEL",       "Ocasión": "INDIVIDUAL", "Precio ($)": 5.34, "Gramaje (g)": 40, "SOM (%)": 0.21},
    ],
}
