PLANTILLAS = {
    "DT - MAÍZ": [
        {"Producto": "Mini Takis 35g", "Fabricante": "BARCEL", "Ocasión": "BITES", "Precio ($)": 10.0, "Gramaje (g)": 35, "SOM (%)": 0.35},
        {"Producto": "Churrumais 70g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 70, "SOM (%)": 2.69},
        {"Producto": "Tostachos 75g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 75, "SOM (%)": 0.53},
        {"Producto": "Runners 72g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 72, "SOM (%)": 3.74},
        {"Producto": "Chipotles 65g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 65, "SOM (%)": 1.11},
        {"Producto": "Fritos 60g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 60, "SOM (%)": 6.77},
        {"Producto": "Rancheritos 58g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 58, "SOM (%)": 3.53},
        {"Producto": "Takis 70g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 70, "SOM (%)": 14.12},
        {"Producto": "Doritos Dinamita 70g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 70, "SOM (%)": 8.76},
        {"Producto": "Tostitos 62g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 62, "SOM (%)": 7.06},
        {"Producto": "Doritos 58g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 58, "SOM (%)": 22.25},
        {"Producto": "Doritos Dinamita 120g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 120, "SOM (%)": 1.94},
        {"Producto": "Tostitos 110g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 110, "SOM (%)": 1.96},
        {"Producto": "Doritos 100g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 100, "SOM (%)": 5.92},
        {"Producto": "Doritos Nacho 146g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 146, "SOM (%)": 0.0},
        {"Producto": "Rancheritos 145g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 145, "SOM (%)": 0.48},
        {"Producto": "Runners 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 40.0, "Gramaje (g)": 200, "SOM (%)": 0.02},
        {"Producto": "Churrumais 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 185, "SOM (%)": 0.06},
        {"Producto": "Tostitos 175g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 175, "SOM (%)": 1.53},
        {"Producto": "Fritos 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 170, "SOM (%)": 0.24},
        {"Producto": "Takis 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 45.0, "Gramaje (g)": 200, "SOM (%)": 0.7},
        {"Producto": "Doritos 245g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 245, "SOM (%)": 1.13},
    ],

    "DT - PAPA": [
        {"Producto": "Papa Barcel 28g", "Fabricante": "BARCEL", "Ocasión": "BITES", "Precio ($)": 10.0, "Gramaje (g)": 28, "SOM (%)": 0.2},
        {"Producto": "Chips 42g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 42, "SOM (%)": 0.1},
        {"Producto": "Wapas 52g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 16.0, "Gramaje (g)": 52, "SOM (%)": 0.3},
        {"Producto": "Papa Barcel 45g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 16.0, "Gramaje (g)": 45, "SOM (%)": 0.0},
        {"Producto": "Papatinas 31g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 16.0, "Gramaje (g)": 31, "SOM (%)": 0.0},
        {"Producto": "Receta Crujiente 57g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 57, "SOM (%)": 5.6},
        {"Producto": "Chips 52g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 52, "SOM (%)": 14.8},
        {"Producto": "Ruffles 48g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 48, "SOM (%)": 17.7},
        {"Producto": "Sabritas 45g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 45, "SOM (%)": 19.3},
        {"Producto": "Ruffles Mega Crunch 42g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 42, "SOM (%)": 4.1},
        {"Producto": "Papas Sol 100g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 100, "SOM (%)": 5.0},
        {"Producto": "Totis Paps 90g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 90, "SOM (%)": 0.2},
        {"Producto": "Papas Sabritones 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 90, "SOM (%)": 0.0},
        {"Producto": "Chidas 85g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 85, "SOM (%)": 2.6},
        {"Producto": "Ruffles Queso 88g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 88, "SOM (%)": 5.3},
        {"Producto": "Receta Crujiente FH 81g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 81, "SOM (%)": 3.7},
        {"Producto": "Sabritas 74g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 74, "SOM (%)": 3.0},
        {"Producto": "Chips 77g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 77, "SOM (%)": 0.1},
        {"Producto": "Ruffles Queso 145g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 145, "SOM (%)": 1.2},
        {"Producto": "Sabritas 105g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 105, "SOM (%)": 0.9},
        {"Producto": "Receta Crujiente 100g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 100, "SOM (%)": 0.1},
        {"Producto": "Papa Barcel Toreadas 170g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 55.0, "Gramaje (g)": 170, "SOM (%)": 0.4},
        {"Producto": "Chips 170g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 55.0, "Gramaje (g)": 170, "SOM (%)": 5.7},
        {"Producto": "Ruffles 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 185, "SOM (%)": 0.8},
        {"Producto": "Sabritas 171g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 171, "SOM (%)": 1.9},
        {"Producto": "Receta Crujiente 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 160, "SOM (%)": 0.4},
    ],

    "DT - MIXES": [
        {"Producto": "Enkanton 46g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 46, "SOM (%)": 0.2},
        {"Producto": "Paketaxo Dark 44g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 44, "SOM (%)": 2.5},
        {"Producto": "Cheetos Mix 41g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 41, "SOM (%)": 2.3},
        {"Producto": "Big Mix 38g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 38, "SOM (%)": 0.0},
        {"Producto": "Paketaxo 35g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 35, "SOM (%)": 2.6},
        {"Producto": "Encanto 80g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 15.0, "Gramaje (g)": 80, "SOM (%)": 0.2},
        {"Producto": "Los Coyotes 75g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 15.0, "Gramaje (g)": 75, "SOM (%)": 0.3},
        {"Producto": "Mix Bokados 85g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 17.0, "Gramaje (g)": 85, "SOM (%)": 2.1},
        {"Producto": "Takis Duoz Takis + Chips 70g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 70, "SOM (%)": 0.6},
        {"Producto": "Doritos Mix 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 90, "SOM (%)": 1.0},
        {"Producto": "Cheetos Mix 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 90, "SOM (%)": 1.4},
        {"Producto": "Paketaxo Dark 88g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 88, "SOM (%)": 0.1},
        {"Producto": "Paketaxo 81g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 81, "SOM (%)": 30.3},
        {"Producto": "Big Mix 80g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 80, "SOM (%)": 22.3},
        {"Producto": "Ruffles Mix 70g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 70, "SOM (%)": 1.3},
        {"Producto": "Paketaxo Mezcladito 110g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 25.0, "Gramaje (g)": 110, "SOM (%)": 0.0},
        {"Producto": "Big Mix 185g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 40.0, "Gramaje (g)": 185, "SOM (%)": 1.2},
        {"Producto": "Paketaxo Mezcladito 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 170, "SOM (%)": 3.1},
        {"Producto": "Paketaxo FH 215g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 215, "SOM (%)": 2.2},
        {"Producto": "Paketaxo Queso 208g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 208, "SOM (%)": 8.2},
        {"Producto": "Paketaxo Dark 208g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 208, "SOM (%)": 1.0},
        {"Producto": "Paketaxo Mezcladito 265g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 59.0, "Gramaje (g)": 265, "SOM (%)": 4.9},
        {"Producto": "Paketaxo Botanero 255g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 59.0, "Gramaje (g)": 255, "SOM (%)": 2.3},
    ],

    "DT - EXTRUIDO Y PELLET": [
        {"Producto": "Leo Ke Chidos 48g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 48, "SOM (%)": 0.4},
        {"Producto": "Leo Papiringas 38g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 38, "SOM (%)": 0.8},
        {"Producto": "Takis Pix 65g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 65, "SOM (%)": 0.5},
        {"Producto": "Prispas 50g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 50, "SOM (%)": 1.5},
        {"Producto": "Valentones 60g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 16.0, "Gramaje (g)": 60, "SOM (%)": 0.31},
        {"Producto": "Sabritones 60g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 16.0, "Gramaje (g)": 60, "SOM (%)": 0.8},
        {"Producto": "Chettos Torciditos 58g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 58, "SOM (%)": 37.1},
        {"Producto": "Chetos Bolitas 46g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 46, "SOM (%)": 5.33},
        {"Producto": "Chettos Pofs 44g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 44, "SOM (%)": 5.4},
        {"Producto": "Chetos Comillos 27g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 27, "SOM (%)": 1.41},
        {"Producto": "Crujitos 42g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 42, "SOM (%)": 3.4},
        {"Producto": "Doritos 3D 40g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 40, "SOM (%)": 1.12},
        {"Producto": "Cheetos Torciditos 115g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 25.0, "Gramaje (g)": 115, "SOM (%)": 19.9},
        {"Producto": "Valentones 175g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 40.0, "Gramaje (g)": 175, "SOM (%)": 0.99},
        {"Producto": "Sabritones 165g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 165, "SOM (%)": 0.69},
        {"Producto": "Cheetos Torciditos 145g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 145, "SOM (%)": 2.4},
        {"Producto": "Cheetos Torciditos 240g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 56.0, "Gramaje (g)": 240, "SOM (%)": 0.6},
    ],

    "DT - CHICHARRÓN": [
        {"Producto": "Encanto Chicharron de Cerdo 35g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 35, "SOM (%)": 2.97},
        {"Producto": "Leo Chicharron de Cerdo 35g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 35, "SOM (%)": 6.81},
        {"Producto": "Bokados Chicharron de Cerdo 30g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 30, "SOM (%)": 4.48},
        {"Producto": "Barcel Chicharron de Cerdo 30g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 30, "SOM (%)": 8.32},
        {"Producto": "Sabritas Chicharron de Cerdo 30g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 30, "SOM (%)": 26.6},
        {"Producto": "Leo Chicharron de Cerdo 60g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 25.0, "Gramaje (g)": 60, "SOM (%)": 0.0},
        {"Producto": "Bokados Chicharron de Cerdo 55g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 25.0, "Gramaje (g)": 55, "SOM (%)": 3.39},
        {"Producto": "Barcel Chicharron de Cerdo 70g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 35.0, "Gramaje (g)": 70, "SOM (%)": 6.94},
        {"Producto": "Sabritas Chicharron de Cerdo 70g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 42.0, "Gramaje (g)": 70, "SOM (%)": 0.19},
        {"Producto": "Petunia Chicharron de Cerdo 120g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 120, "SOM (%)": 2.0},
        {"Producto": "Bokados Chicharron de Cerdo 115g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 56.0, "Gramaje (g)": 115, "SOM (%)": 2.31},
        {"Producto": "Sabritas Chicharron de Cerdo 115g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 115, "SOM (%)": 2.8},
    ],

    "DT - PALOMITAS DULCES": [
        {"Producto": "Karameladas Pop 45g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 45, "SOM (%)": 10.72},
        {"Producto": "Act II Caramelo 42g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 17.0, "Gramaje (g)": 42, "SOM (%)": 0.96},
        {"Producto": "Act II Caramelo 95g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 95, "SOM (%)": 1.13},
        {"Producto": "Karameladas Pop 110g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 16.0, "Gramaje (g)": 110, "SOM (%)": 49.19},
    ],

    "DT - PALOMITAS SALADAS": [
        {"Producto": "WPC Queso Cheddar 35g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 14.0, "Gramaje (g)": 35, "SOM (%)": 0.0},
        {"Producto": "Cheetos Palomitas 29g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 17.0, "Gramaje (g)": 29, "SOM (%)": 15.12},
        {"Producto": "Act II Chile y Limón 25g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 17.0, "Gramaje (g)": 25, "SOM (%)": 0.51},
        {"Producto": "Act II Infierno 21g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 17.0, "Gramaje (g)": 21, "SOM (%)": 0.35},
        {"Producto": "Act II Queso Cheddar 21g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 17.0, "Gramaje (g)": 21, "SOM (%)": 0.71},
        {"Producto": "Act II Mantequilla 17g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 17.0, "Gramaje (g)": 17, "SOM (%)": 0.65},
        {"Producto": "Pop Queso Cheddar 45g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 16.0, "Gramaje (g)": 45, "SOM (%)": 6.06},
        {"Producto": "Act II Queso Cheddar 45g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 45, "SOM (%)": 0.74},
        {"Producto": "Act II Infierno 38g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 38, "SOM (%)": 0.01},
        {"Producto": "Act II Mantequilla 35g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 35, "SOM (%)": 0.0},
    ],

    "DT - CACAHUATE CUBIERTO": [
        {"Producto": "Kacang Cubierto 77g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 77, "SOM (%)": 26.16},
        {"Producto": "Kacang Xferas 60g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 60, "SOM (%)": 0.32},
        {"Producto": "Hot Nuts 75g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 75, "SOM (%)": 31.68},
        {"Producto": "Kacang Cubierto 130g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 130, "SOM (%)": 20.44},
        {"Producto": "Hot Nuts 115g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 115, "SOM (%)": 18.93},
    ],

    "DT - CACAHUATE FRITO": [
        {"Producto": "Cacahuate Leo 80g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 80, "SOM (%)": 4.24},
        {"Producto": "Golden Nuts 78g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 78, "SOM (%)": 30.92},
        {"Producto": "Bokados 100g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 17.0, "Gramaje (g)": 100, "SOM (%)": 2.56},
        {"Producto": "Kacang Frito 77g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 77, "SOM (%)": 14.4},
        {"Producto": "Golden Nuts 110g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 110, "SOM (%)": 18.18},
    ],

    "DT - CACAHUATE JAPONÉS": [
        {"Producto": "Encanto 60g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 60, "SOM (%)": 0.4},
        {"Producto": "Karate 65g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 12.0, "Gramaje (g)": 65, "SOM (%)": 4.1},
        {"Producto": "Kiyakis 60g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 60, "SOM (%)": 10.9},
        {"Producto": "Karate 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 16.0, "Gramaje (g)": 90, "SOM (%)": 0.27},
        {"Producto": "Kiyakis 120g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 120, "SOM (%)": 13.62},
        {"Producto": "Karate 110g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 110, "SOM (%)": 41.04},
        {"Producto": "Karate 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 25.0, "Gramaje (g)": 185, "SOM (%)": 0.22},
    ],

    "AS - MAÍZ": [
        {"Producto": "Rancheritos Clasico 40g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 40, "SOM (%)": 1.3},
        {"Producto": "Fritos 38g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 38, "SOM (%)": 1.37},
        {"Producto": "Churrumais 36g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 36, "SOM (%)": 0.58},
        {"Producto": "Doritos Nachos 23g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 23, "SOM (%)": 3.24},
        {"Producto": "Tostitos 55g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 12.0, "Gramaje (g)": 55, "SOM (%)": 25.5},
        {"Producto": "Rancheritos 72g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 72, "SOM (%)": 0.51},
        {"Producto": "Fritos 70g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 70, "SOM (%)": 0.74},
        {"Producto": "Doritos 58g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 18.0, "Gramaje (g)": 58, "SOM (%)": 1.9},
        {"Producto": "Takis 94g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 94, "SOM (%)": 1.56},
        {"Producto": "Doritos Nacho 76g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 76, "SOM (%)": 2.13},
        {"Producto": "Doritos 146g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 146, "SOM (%)": 2.69},
        {"Producto": "Rancheritos 145g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 145, "SOM (%)": 1.23},
        {"Producto": "Doritos Dinamita 220g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 220, "SOM (%)": 0.92},
        {"Producto": "Churrumais 200g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 200, "SOM (%)": 1.34},
        {"Producto": "Tostitos 174g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 174, "SOM (%)": 0.58},
        {"Producto": "Fritos 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 170, "SOM (%)": 3.29},
        {"Producto": "Chipotles 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 45.0, "Gramaje (g)": 200, "SOM (%)": 0.47},
        {"Producto": "Fritos 250g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 53.0, "Gramaje (g)": 250, "SOM (%)": 0.81},
        {"Producto": "Runners 280g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 280, "SOM (%)": 0.67},
        {"Producto": "Takis 240g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 240, "SOM (%)": 6.35},
        {"Producto": "Tostitos SV y FH 240g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 240, "SOM (%)": 6.04},
        {"Producto": "Rancheritos 225g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 225, "SOM (%)": 0.64},
        {"Producto": "Doritos 223g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 223, "SOM (%)": 11.16},
        {"Producto": "Tostitos Sal 400g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 61.0, "Gramaje (g)": 400, "SOM (%)": 2.49},
        {"Producto": "Takis 340g", "Fabricante": "BARCEL", "Ocasión": "REUNIÓN", "Precio ($)": 80.0, "Gramaje (g)": 340, "SOM (%)": 0.7},
        {"Producto": "Doritos 335g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 86.0, "Gramaje (g)": 335, "SOM (%)": 3.46},
    ],

    "AS - PAPA": [
        {"Producto": "Ruffles Queso 20g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 20, "SOM (%)": 0.79},
        {"Producto": "Sabritas 18g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 18, "SOM (%)": 0.72},
        {"Producto": "Mini Chips (e. BA, BAE y MB) 18g", "Fabricante": "BARCEL", "Ocasión": "BITES", "Precio ($)": 10.0, "Gramaje (g)": 18, "SOM (%)": 0.0},
        {"Producto": "Receta Crujiente 41g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 12.0, "Gramaje (g)": 41, "SOM (%)": 4.73},
        {"Producto": "Ruffles MC 46g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 46, "SOM (%)": 3.0},
        {"Producto": "Sabritas 42g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 42, "SOM (%)": 2.7},
        {"Producto": "Chip's 42g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 42, "SOM (%)": 0.54},
        {"Producto": "Sabritas 57g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 25.0, "Gramaje (g)": 57, "SOM (%)": 0.0},
        {"Producto": "Chip's 55g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 25.0, "Gramaje (g)": 55, "SOM (%)": 1.25},
        {"Producto": "Ruffles Queso 67g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 67, "SOM (%)": 1.44},
        {"Producto": "Chip's 100g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 40.0, "Gramaje (g)": 100, "SOM (%)": 0.42},
        {"Producto": "Ruffles 120g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 120, "SOM (%)": 3.12},
        {"Producto": "Sabritas 105g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 105, "SOM (%)": 2.96},
        {"Producto": "Chips Papatinas Chilix 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 55.0, "Gramaje (g)": 200, "SOM (%)": 0.62},
        {"Producto": "Papa Barcel 170g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 55.0, "Gramaje (g)": 170, "SOM (%)": 0.83},
        {"Producto": "Chip's (EW) 160g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 160, "SOM (%)": 6.25},
        {"Producto": "Chip's 150g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 150, "SOM (%)": 7.22},
        {"Producto": "Receta Crujiente 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 160, "SOM (%)": 8.76},
        {"Producto": "Ruffles 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 185, "SOM (%)": 11.45},
        {"Producto": "Sabritas 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 160, "SOM (%)": 16.64},
        {"Producto": "Sabritas Sensaciones 150g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 150, "SOM (%)": 0.35},
        {"Producto": "Chips Toque Maestro 140g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 62.0, "Gramaje (g)": 140, "SOM (%)": 0.57},
        {"Producto": "Chips 240g", "Fabricante": "BARCEL", "Ocasión": "REUNIÓN", "Precio ($)": 85.0, "Gramaje (g)": 240, "SOM (%)": 3.46},
        {"Producto": "Ruffles Queso 278g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 86.0, "Gramaje (g)": 278, "SOM (%)": 2.81},
        {"Producto": "Sabritas 240g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 86.0, "Gramaje (g)": 240, "SOM (%)": 2.45},
        {"Producto": "Receta Crujiente 240g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 86.0, "Gramaje (g)": 240, "SOM (%)": 0.69},
    ],

    "AS - MIXES": [
        {"Producto": "Paketaxo (PP) 41g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 41, "SOM (%)": 15.85},
        {"Producto": "Doritos Mix 62g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 15.0, "Gramaje (g)": 62, "SOM (%)": 0.91},
        {"Producto": "Paketaxo 62g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 15.0, "Gramaje (g)": 62, "SOM (%)": 1.67},
        {"Producto": "Cheetos Mix 55g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 15.0, "Gramaje (g)": 55, "SOM (%)": 1.31},
        {"Producto": "Ruffles Mix 45g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 15.0, "Gramaje (g)": 45, "SOM (%)": 1.4},
        {"Producto": "Paketaxo Mezcladito 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 170, "SOM (%)": 1.18},
        {"Producto": "Big Mix 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 200, "SOM (%)": 5.37},
        {"Producto": "Paketaxo Botanero 255g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 255, "SOM (%)": 7.72},
        {"Producto": "Paketaxo FH 215g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 215, "SOM (%)": 4.76},
        {"Producto": "Paketaxo Queso 208g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 208, "SOM (%)": 17.89},
        {"Producto": "Paketaxo Dark 208g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 208, "SOM (%)": 5.62},
        {"Producto": "Doritos Mix 205g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 205, "SOM (%)": 2.62},
        {"Producto": "Cheetos Mix 190g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 190, "SOM (%)": 4.13},
        {"Producto": "Ruffles Mix 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 61.0, "Gramaje (g)": 170, "SOM (%)": 2.61},
        {"Producto": "Paketaxo Mezcladito 265g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 61.0, "Gramaje (g)": 265, "SOM (%)": 13.53},
        {"Producto": "Paketaxo Queso 313g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 86.0, "Gramaje (g)": 313, "SOM (%)": 3.86},
    ],

    "AS - EXTRUIDO Y PELLET": [
        {"Producto": "Cheetos 18g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 8.5, "Gramaje (g)": 18, "SOM (%)": 1.5},
        {"Producto": "Takis Pix 45g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 45, "SOM (%)": 0.71},
        {"Producto": "Doritos 3´D 40g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 40, "SOM (%)": 2.6},
        {"Producto": "Cheetos Poffs FH 35g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 35, "SOM (%)": 0.5},
        {"Producto": "Crujitos 35g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 35, "SOM (%)": 6.28},
        {"Producto": "Cheetos Bolitas 34g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 34, "SOM (%)": 5.83},
        {"Producto": "Chetos Colmillos 28g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 28, "SOM (%)": 2.1},
        {"Producto": "Cheetos Torciditos (PP) 61g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 61, "SOM (%)": 1.46},
        {"Producto": "Cheetos Torciditos (PP) 55g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 55, "SOM (%)": 2.05},
        {"Producto": "Cheetos Torciditos 82g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 82, "SOM (%)": 3.35},
        {"Producto": "Leo Papirringas 100g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 25.0, "Gramaje (g)": 100, "SOM (%)": 1.06},
        {"Producto": "Cheetos Bolitas 110g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 110, "SOM (%)": 2.16},
        {"Producto": "Cheetos Poffs 110g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 110, "SOM (%)": 2.29},
        {"Producto": "Valentones 175g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 36.0, "Gramaje (g)": 175, "SOM (%)": 0.26},
        {"Producto": "Sabritones 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 160, "SOM (%)": 3.39},
        {"Producto": "Cheetos Torciditos 145g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 145, "SOM (%)": 9.56},
        {"Producto": "Quesabritas 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 50.0, "Gramaje (g)": 170, "SOM (%)": 5.1},
        {"Producto": "Sabritones 260g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 61.0, "Gramaje (g)": 260, "SOM (%)": 0.0},
        {"Producto": "Cheetos Torciditos 240g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 61.0, "Gramaje (g)": 240, "SOM (%)": 24.99},
    ],

    "AS - CHICHARRÓN": [
        {"Producto": "Otras Marcas 70g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 70, "SOM (%)": 5.55},
        {"Producto": "Bokados Chicharron de Cerdo 67g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 35.0, "Gramaje (g)": 67, "SOM (%)": 3.02},
        {"Producto": "Sabritas Chicharron de Cerdo 70g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 37.0, "Gramaje (g)": 70, "SOM (%)": 0.0},
        {"Producto": "Otras Marcas 100g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 100, "SOM (%)": 10.22},
        {"Producto": "Barcel Chicharron de Cerdo 90g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 50.0, "Gramaje (g)": 90, "SOM (%)": 3.63},
        {"Producto": "Spirrones 100g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 55.0, "Gramaje (g)": 100, "SOM (%)": 5.41},
        {"Producto": "Sabritas Chicharron de Cerdo 105g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 57.0, "Gramaje (g)": 105, "SOM (%)": 24.83},
        {"Producto": "Bokados Chicharron de Cerdo 115g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 65.0, "Gramaje (g)": 115, "SOM (%)": 5.39},
        {"Producto": "Otras Marcas 200g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 65.0, "Gramaje (g)": 200, "SOM (%)": 5.14},
        {"Producto": "Bokados Chicharron de Cerdo 210g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 85.0, "Gramaje (g)": 210, "SOM (%)": 2.71},
    ],

    "AS - PALOMITA DULCE": [
        {"Producto": "Slim Pop Sweet & Salty 25g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 13.0, "Gramaje (g)": 25, "SOM (%)": 0.61},
        {"Producto": "Pop Karameladas (PP) 40g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 40, "SOM (%)": 6.0},
        {"Producto": "Pop Karameladas 90g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 17.0, "Gramaje (g)": 90, "SOM (%)": 8.93},
        {"Producto": "Act II Caramelo 95g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 95, "SOM (%)": 1.1},
        {"Producto": "Pop Karameladas 120g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 30.0, "Gramaje (g)": 120, "SOM (%)": 3.5},
        {"Producto": "Act II Caramelo 175g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 175, "SOM (%)": 3.6},
        {"Producto": "Slim Pop Sweet & Salty 125g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 45.0, "Gramaje (g)": 125, "SOM (%)": 4.0},
        {"Producto": "Pop Karameladas 240g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 240, "SOM (%)": 10.61},
    ],

    "AS - PALOMITA SALADA": [
        {"Producto": "Poffets Queso 24g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 10.0, "Gramaje (g)": 24, "SOM (%)": 10.54},
        {"Producto": "Pop Cheddar (PP) 23g", "Fabricante": "BARCEL", "Ocasión": "BITES", "Precio ($)": 10.0, "Gramaje (g)": 23, "SOM (%)": 1.09},
        {"Producto": "Slim Pop 18g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 14.0, "Gramaje (g)": 18, "SOM (%)": 2.12},
        {"Producto": "Act II Chile y Limon 50g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 50, "SOM (%)": 0.64},
        {"Producto": "Act II Queso Cheddar 45g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 45, "SOM (%)": 0.69},
        {"Producto": "Pop Cheddar 110g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 40.0, "Gramaje (g)": 110, "SOM (%)": 0.9},
        {"Producto": "Act II Balance 130g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 130, "SOM (%)": 1.2},
        {"Producto": "Act II 110g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 110, "SOM (%)": 4.83},
        {"Producto": "Act II Queso Cheddar e Infierno 90g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 90, "SOM (%)": 4.2},
        {"Producto": "Slim Pop Total Sabores 110g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 45.0, "Gramaje (g)": 110, "SOM (%)": 18.99},
        {"Producto": "Netflix Mantequilla 90g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 53.0, "Gramaje (g)": 90, "SOM (%)": 0.2},
        {"Producto": "Act II 160g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 54.0, "Gramaje (g)": 160, "SOM (%)": 3.24},
    ],

    "AS - CACAHUATE CUBIERTO": [
        {"Producto": "Kacang Cheetos 60g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 60, "SOM (%)": 10.2},
        {"Producto": "Kacang Incógnita y FH 50g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 50, "SOM (%)": 2.9},
        {"Producto": "Kacang Xferas 80g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 80, "SOM (%)": 0.0},
        {"Producto": "Kacang 110g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 27.0, "Gramaje (g)": 110, "SOM (%)": 7.4},
        {"Producto": "Hot Nuts 100g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 27.0, "Gramaje (g)": 100, "SOM (%)": 21.38},
        {"Producto": "Kacang Xferas 137g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 37.0, "Gramaje (g)": 137, "SOM (%)": 0.0},
        {"Producto": "Hot Nuts 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 42.0, "Gramaje (g)": 200, "SOM (%)": 30.49},
        {"Producto": "Kacang 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 44.0, "Gramaje (g)": 185, "SOM (%)": 16.48},
    ],

    "AS - CACAHUATE FRITO": [
        {"Producto": "Mafer Frito 65g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 65, "SOM (%)": 4.57},
        {"Producto": "Coolnuts Frito 50g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 50, "SOM (%)": 0.03},
        {"Producto": "Golden Nuts 100g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 27.0, "Gramaje (g)": 100, "SOM (%)": 5.0},
        {"Producto": "Kacang Frito 100g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 27.0, "Gramaje (g)": 100, "SOM (%)": 1.59},
        {"Producto": "Mafer Frito 120g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 32.0, "Gramaje (g)": 120, "SOM (%)": 0.0},
        {"Producto": "Golden Nuts 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 40.0, "Gramaje (g)": 200, "SOM (%)": 4.35},
        {"Producto": "Mafer Frito 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 46.0, "Gramaje (g)": 170, "SOM (%)": 0.0},
        {"Producto": "Mafer Frito 240g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 240, "SOM (%)": 14.97},
    ],

    "AS - CACAHUATE JAPONÉS": [
        {"Producto": "Karate 75g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 10.0, "Gramaje (g)": 75, "SOM (%)": 14.57},
        {"Producto": "Mafer 65g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 65, "SOM (%)": 3.47},
        {"Producto": "Karate 115g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 20.0, "Gramaje (g)": 115, "SOM (%)": 15.68},
        {"Producto": "Karate 180g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 25.0, "Gramaje (g)": 180, "SOM (%)": 20.67},
        {"Producto": "Kiyakis 150g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 25.0, "Gramaje (g)": 150, "SOM (%)": 12.23},
        {"Producto": "Mafer 230g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 59.0, "Gramaje (g)": 240, "SOM (%)": 16.62},
    ],

    "CNV - MAÍZ": [
        {"Producto": "Takis 56g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 56, "SOM (%)": 0.8},
        {"Producto": "Fritos 70g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 70, "SOM (%)": 5.1},
        {"Producto": "Doritos Dinamita 70g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 70, "SOM (%)": 5.6},
        {"Producto": "Churrumais 64g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 64, "SOM (%)": 1.8},
        {"Producto": "Tostitos 62g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 62, "SOM (%)": 5.0},
        {"Producto": "Doritos 58g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 58, "SOM (%)": 12.4},
        {"Producto": "Rancheritos 52g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 52, "SOM (%)": 3.5},
        {"Producto": "Chipotles 80g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 28.0, "Gramaje (g)": 80, "SOM (%)": 1.7},
        {"Producto": "Runners 80g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 28.0, "Gramaje (g)": 80, "SOM (%)": 3.0},
        {"Producto": "Takis 80g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 80, "SOM (%)": 7.7},
        {"Producto": "Takis Blue Heat 75g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 75, "SOM (%)": 0.7},
        {"Producto": "Doritos Dinamita 120g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 35.0, "Gramaje (g)": 120, "SOM (%)": 1.4},
        {"Producto": "Doritos 100g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 35.0, "Gramaje (g)": 110, "SOM (%)": 4.1},
        {"Producto": "Doritos Nacho 146g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 146, "SOM (%)": 4.3},
        {"Producto": "Rancheritos 145g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 145, "SOM (%)": 2.5},
        {"Producto": "Tostitos 115g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 35.0, "Gramaje (g)": 115, "SOM (%)": 2.7},
        {"Producto": "Doritos Dinamita 220g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 220, "SOM (%)": 2.1},
        {"Producto": "Tostitos 200g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 200, "SOM (%)": 0.7},
        {"Producto": "Churrumais 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 185, "SOM (%)": 1.0},
        {"Producto": "Fritos 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 170, "SOM (%)": 2.3},
        {"Producto": "Takis 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 58.0, "Gramaje (g)": 200, "SOM (%)": 2.7},
        {"Producto": "Tostitos 240g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 64.0, "Gramaje (g)": 240, "SOM (%)": 3.9},
        {"Producto": "Doritos 223g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 64.0, "Gramaje (g)": 223, "SOM (%)": 10.0},
        {"Producto": "Takis 260g", "Fabricante": "BARCEL", "Ocasión": "REUNIÓN", "Precio ($)": 65.0, "Gramaje (g)": 260, "SOM (%)": 1.5},
        {"Producto": "Doritos Nacho 335g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 95.0, "Gramaje (g)": 335, "SOM (%)": 4.1},
    ],

    "CNV - PAPAS": [
        {"Producto": "Ruffles 48g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 48, "SOM (%)": 7.0},
        {"Producto": "Chips 42g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 42, "SOM (%)": 0.1},
        {"Producto": "Sabritas Originales 42g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 42, "SOM (%)": 6.0},
        {"Producto": "Sabritas RC 57g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 29.0, "Gramaje (g)": 57, "SOM (%)": 2.3},
        {"Producto": "Chips 60g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 32.0, "Gramaje (g)": 60, "SOM (%)": 9.8},
        {"Producto": "Ruffles 88g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 35.0, "Gramaje (g)": 88, "SOM (%)": 3.0},
        {"Producto": "Sabritas 74g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 35.0, "Gramaje (g)": 74, "SOM (%)": 3.2},
        {"Producto": "Papa Barcel 90g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 39.0, "Gramaje (g)": 90, "SOM (%)": 0.0},
        {"Producto": "Papatinas 90g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 42.0, "Gramaje (g)": 90, "SOM (%)": 0.7},
        {"Producto": "Chips 100g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 49.0, "Gramaje (g)": 100, "SOM (%)": 0.7},
        {"Producto": "Ruffles 120g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 120, "SOM (%)": 3.1},
        {"Producto": "Sabritas 105g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 105, "SOM (%)": 2.8},
        {"Producto": "Pringles 124g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 124, "SOM (%)": 3.8},
        {"Producto": "Papatinas 200g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 54.0, "Gramaje (g)": 200, "SOM (%)": 0.0},
        {"Producto": "Papa Barcel 170g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 170, "SOM (%)": 1.1},
        {"Producto": "Sabritas RC 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 62.0, "Gramaje (g)": 160, "SOM (%)": 6.5},
        {"Producto": "Ruffles 185g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 64.0, "Gramaje (g)": 185, "SOM (%)": 8.1},
        {"Producto": "Sabritas 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 64.0, "Gramaje (g)": 160, "SOM (%)": 8.7},
        {"Producto": "Chips 170g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 65.0, "Gramaje (g)": 170, "SOM (%)": 19.6},
        {"Producto": "Ruffles 278g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 95.0, "Gramaje (g)": 278, "SOM (%)": 2.6},
        {"Producto": "Sabritas 240g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 95.0, "Gramaje (g)": 240, "SOM (%)": 1.6},
    ],

    "CNV - MIXES": [
        {"Producto": "Big Mix 55g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 55, "SOM (%)": 0.1},
        {"Producto": "Paketaxo 41g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 41, "SOM (%)": 1.4},
        {"Producto": "Big Mix Queso 75g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 24.0, "Gramaje (g)": 75, "SOM (%)": 0.0},
        {"Producto": "Mix Bokados 85g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 27.0, "Gramaje (g)": 85, "SOM (%)": 2.1},
        {"Producto": "Encanto 100g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 100, "SOM (%)": 0.6},
        {"Producto": "Cheetos Mix 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 90, "SOM (%)": 0.2},
        {"Producto": "Doritos Mix 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 90, "SOM (%)": 0.1},
        {"Producto": "Paketaxo 81g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 81, "SOM (%)": 1.2},
        {"Producto": "Ruffles Mix 70g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 30.0, "Gramaje (g)": 70, "SOM (%)": 0.2},
        {"Producto": "Mix Bokados 210g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 38.0, "Gramaje (g)": 210, "SOM (%)": 2.7},
        {"Producto": "Big Mix 185g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 50.0, "Gramaje (g)": 185, "SOM (%)": 7.2},
        {"Producto": "Big Mix Salsa Inglesa 170g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 50.0, "Gramaje (g)": 170, "SOM (%)": 1.2},
        {"Producto": "Paketaxo Mezcladito 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 170, "SOM (%)": 0.1},
        {"Producto": "Paketaxo Botanero 255g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 255, "SOM (%)": 8.7},
        {"Producto": "Paquetaxo Flamin Hot 215g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 215, "SOM (%)": 5.3},
        {"Producto": "Paketaxo Dark 208g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 208, "SOM (%)": 7.8},
        {"Producto": "Paketaxo Queso 208g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 208, "SOM (%)": 22.8},
        {"Producto": "Doritos Mix 205g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 67.0, "Gramaje (g)": 205, "SOM (%)": 2.3},
        {"Producto": "Cheetos Mix 190g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 67.0, "Gramaje (g)": 190, "SOM (%)": 4.5},
        {"Producto": "Ruffles Mix 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 67.0, "Gramaje (g)": 170, "SOM (%)": 4.4},
        {"Producto": "Paketaxo Mezcladito 265g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 60.0, "Gramaje (g)": 265, "SOM (%)": 18.9},
        {"Producto": "Paketaxo Queso 313g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 94.5, "Gramaje (g)": 313, "SOM (%)": 3.8},
    ],

    "CNV - EXTRUIDO Y PELLET": [
        {"Producto": "Takis Pix 45g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 45, "SOM (%)": 0.6},
        {"Producto": "Leo Papirringas 46g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 20.0, "Gramaje (g)": 46, "SOM (%)": 1.0},
        {"Producto": "Prispas 50g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 50, "SOM (%)": 1.0},
        {"Producto": "Cheetos Torciditos 58g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 58, "SOM (%)": 27.8},
        {"Producto": "Cheetos Bolitas 46g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 46, "SOM (%)": 2.4},
        {"Producto": "Cheetos Poffs 44g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 44, "SOM (%)": 1.9},
        {"Producto": "Cheetos Colmillos 31g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 24.0, "Gramaje (g)": 31, "SOM (%)": 1.2},
        {"Producto": "Crujitos 42g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 26.0, "Gramaje (g)": 42, "SOM (%)": 1.5},
        {"Producto": "Cheetos Torciditos 115g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 35.0, "Gramaje (g)": 115, "SOM (%)": 14.6},
        {"Producto": "Cheetos Bolitas 110g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 110, "SOM (%)": 2.0},
        {"Producto": "Cheetos Poffs 110g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 110, "SOM (%)": 2.1},
        {"Producto": "Cheetos Colmillos 100g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 100, "SOM (%)": 0.1},
        {"Producto": "Prispas 130g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 38.0, "Gramaje (g)": 130, "SOM (%)": 1.3},
        {"Producto": "Valentones 175g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 44.0, "Gramaje (g)": 175, "SOM (%)": 1.8},
        {"Producto": "Sabritones 160g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 160, "SOM (%)": 1.6},
        {"Producto": "Cheetos Torciditos 145g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 145, "SOM (%)": 12.5},
        {"Producto": "Crujitos 130g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 52.0, "Gramaje (g)": 130, "SOM (%)": 1.6},
        {"Producto": "Cheetos Torciditos 240g", "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN", "Precio ($)": 64.0, "Gramaje (g)": 240, "SOM (%)": 12.1},
    ],

    "CNV - CHICHARRÓN": [
        {"Producto": "Leo Chicharron de Cerdo 30g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 30, "SOM (%)": 0.2},
        {"Producto": "Bokados Chicharrón de Cerdo 30g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 30, "SOM (%)": 5.9},
        {"Producto": "Sabritas Chicharron de Cerdo 30g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 26.0, "Gramaje (g)": 30, "SOM (%)": 0.6},
        {"Producto": "Leo Chicharron de Cerdo 60g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 35.0, "Gramaje (g)": 60, "SOM (%)": 4.9},
        {"Producto": "Bokados Chicharrón de Cerdo 55g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 40.0, "Gramaje (g)": 55, "SOM (%)": 10.4},
        {"Producto": "Petunia Chicharron de Cerdo 70g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 42.0, "Gramaje (g)": 70, "SOM (%)": 2.8},
        {"Producto": "Mission Chicharron de Cerdo 113g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 59.0, "Gramaje (g)": 113, "SOM (%)": 4.1},
        {"Producto": "Petunia Chicharron de Cerdo 120g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 65.0, "Gramaje (g)": 120, "SOM (%)": 1.5},
        {"Producto": "Barcel Chicharrón de Cerdo 110g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 65.0, "Gramaje (g)": 110, "SOM (%)": 0.0},
        {"Producto": "Sabritas Chicharron de Cerdo 115g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 74.0, "Gramaje (g)": 115, "SOM (%)": 14.2},
        {"Producto": "Bokados Chicharrón de Cerdo 115g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 75.0, "Gramaje (g)": 115, "SOM (%)": 14.9},
        {"Producto": "Leo Chicharron de Cerdo 130g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 75.0, "Gramaje (g)": 130, "SOM (%)": 7.4},
    ],

    "CNV - PALOMITAS DULCE": [
        {"Producto": "Act II Delix 70g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 70, "SOM (%)": 0.0},
        {"Producto": "Act II Caramelo 95g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 26.0, "Gramaje (g)": 95, "SOM (%)": 3.2},
        {"Producto": "Karameladas Pop 120g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 32.0, "Gramaje (g)": 120, "SOM (%)": 16.6},
        {"Producto": "Slim Pop Sweet & Salty 125g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 45.0, "Gramaje (g)": 125, "SOM (%)": 1.4},
        {"Producto": "Karameladas Pop 260g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 58.0, "Gramaje (g)": 260, "SOM (%)": 0.0},
        {"Producto": "Act II Caramelo 175g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 175, "SOM (%)": 4.8},
    ],

    "CNV - PALOMITA SALADA": [
        {"Producto": "Slim Pop 18g", "Fabricante": "OTROS", "Ocasión": "BITES", "Precio ($)": 16.0, "Gramaje (g)": 18, "SOM (%)": 2.4},
        {"Producto": "Cheetos Palomitas 29g", "Fabricante": "SABRITAS", "Ocasión": "BITES", "Precio ($)": 24.0, "Gramaje (g)": 29, "SOM (%)": 4.1},
        {"Producto": "Pop Queso Cheddar 45g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 45, "SOM (%)": 1.2},
        {"Producto": "Act II Chile Limon 50g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 26.0, "Gramaje (g)": 50, "SOM (%)": 3.2},
        {"Producto": "Act II Queso Cheedar 45g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 26.0, "Gramaje (g)": 45, "SOM (%)": 3.6},
        {"Producto": "Act II Infierno y Balance 38g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 26.0, "Gramaje (g)": 38, "SOM (%)": 2.3},
        {"Producto": "Act II Mantequila 35g", "Fabricante": "OTROS", "Ocasión": "INDIVIDUAL", "Precio ($)": 26.0, "Gramaje (g)": 35, "SOM (%)": 0.0},
        {"Producto": "Act II Chile Limon 110g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 44.0, "Gramaje (g)": 110, "SOM (%)": 3.0},
        {"Producto": "Slim Pop Total Sabores 110g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 44.0, "Gramaje (g)": 110, "SOM (%)": 16.9},
        {"Producto": "Act II Queso Cheddar 90g", "Fabricante": "OTROS", "Ocasión": "COMPARTIR", "Precio ($)": 52.0, "Gramaje (g)": 90, "SOM (%)": 5.8},
        {"Producto": "Wise Popcorn 150g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 45.0, "Gramaje (g)": 150, "SOM (%)": 3.2},
        {"Producto": "Act II Chile Limon 180g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 180, "SOM (%)": 4.1},
        {"Producto": "Act II Queso Chipotle 160g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 160, "SOM (%)": 2.2},
        {"Producto": "Act II Infierno Extremo 150g", "Fabricante": "OTROS", "Ocasión": "FAMILIAR", "Precio ($)": 60.0, "Gramaje (g)": 150, "SOM (%)": 2.4},
    ],

    "CNV - CACAHUATE CUBIERTO": [
        {"Producto": "Hot Nuts 50g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 50, "SOM (%)": 13.5},
        {"Producto": "Kacang 77g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 25.0, "Gramaje (g)": 77, "SOM (%)": 27.8},
        {"Producto": "Kacang Xferas 60g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 25.0, "Gramaje (g)": 60, "SOM (%)": 0.1},
        {"Producto": "Kacang 110g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 35.0, "Gramaje (g)": 110, "SOM (%)": 18.1},
        {"Producto": "Hot Nuts 100g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 35.0, "Gramaje (g)": 100, "SOM (%)": 20.0},
        {"Producto": "Hot Nuts 160g", "Fabricante": "BARCEL", "Ocasión": "FAMILIAR", "Precio ($)": 47.0, "Gramaje (g)": 160, "SOM (%)": 16.0},
    ],

    "CNV - CACAHUATE FRITO": [
        {"Producto": "Golden Nuts 78g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 78, "SOM (%)": 4.9},
        {"Producto": "Mafer 65g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 65, "SOM (%)": 6.9},
        {"Producto": "Golden Nuts 100g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 27.0, "Gramaje (g)": 100, "SOM (%)": 38.7},
        {"Producto": "Cacahuate Bokados 100g", "Fabricante": "OTROS", "Ocasión": "HAMBRE", "Precio ($)": 28.0, "Gramaje (g)": 100, "SOM (%)": 6.9},
        {"Producto": "Mafer 120g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 38.0, "Gramaje (g)": 120, "SOM (%)": 6.4},
        {"Producto": "Golden Nuts 150g", "Fabricante": "BARCEL", "Ocasión": "COMPARTIR", "Precio ($)": 40.0, "Gramaje (g)": 150, "SOM (%)": 8.7},
    ],

    "CNV - CACAHUATE JAPONÉS": [
        {"Producto": "Kiyakis 50g", "Fabricante": "BARCEL", "Ocasión": "INDIVIDUAL", "Precio ($)": 15.0, "Gramaje (g)": 50, "SOM (%)": 9.9},
        {"Producto": "Mafer 65g", "Fabricante": "SABRITAS", "Ocasión": "INDIVIDUAL", "Precio ($)": 22.0, "Gramaje (g)": 65, "SOM (%)": 3.0},
        {"Producto": "Kiyakis 95g", "Fabricante": "BARCEL", "Ocasión": "HAMBRE", "Precio ($)": 22.0, "Gramaje (g)": 95, "SOM (%)": 17.5},
        {"Producto": "Karate 90g", "Fabricante": "SABRITAS", "Ocasión": "HAMBRE", "Precio ($)": 25.0, "Gramaje (g)": 90, "SOM (%)": 16.6},
        {"Producto": "Karate 127g", "Fabricante": "SABRITAS", "Ocasión": "COMPARTIR", "Precio ($)": 33.0, "Gramaje (g)": 127, "SOM (%)": 20.0},
        {"Producto": "Mafer 170g", "Fabricante": "SABRITAS", "Ocasión": "FAMILIAR", "Precio ($)": 50.0, "Gramaje (g)": 170, "SOM (%)": 4.0},
    ],

    "CLUBES - PAQUETES": [
        {"Producto": "SURTIDO DE SABRITAS MINIS PACK 50P (SAMS)",    "Fabricante": "SABRITAS",      "Ocasión": "TRANSFORMADOR", "Precio ($)": 273.13, "Gramaje (g)": 963,  "SOM (%)": 0.0},
        {"Producto": "SURTIDO DE SABRITAS MINIS PACK 50P (COSTCO)",  "Fabricante": "SABRITAS",      "Ocasión": "TRANSFORMADOR", "Precio ($)": 359.0,  "Gramaje (g)": 963,  "SOM (%)": 0.0},
        {"Producto": "SURTIDO DE SABRITAS SABRINEGOCIO 43P (SAMS)",  "Fabricante": "SABRITAS",      "Ocasión": "B2B",           "Precio ($)": 479.77, "Gramaje (g)": 1788, "SOM (%)": 0.0},
        {"Producto": "DORITOS NACHO 25P - 54G (SAMS)",               "Fabricante": "SABRITAS",      "Ocasión": "B2B",           "Precio ($)": 475.69, "Gramaje (g)": 1350, "SOM (%)": 0.0},
        {"Producto": "SURTIDO DE SABRITAS 30P (COSTCO)",             "Fabricante": "SABRITAS",      "Ocasión": "B2B",           "Precio ($)": 419.0,  "Gramaje (g)": 1314, "SOM (%)": 0.0},
        {"Producto": "MIX BARCEL 27P (SAMS)",                        "Fabricante": "BARCEL",        "Ocasión": "B2B",           "Precio ($)": 295.0,  "Gramaje (g)": 1362, "SOM (%)": 0.0},
    ],

    "CLUBES - PAPA": [
        {"Producto": "SABRITAS 255G (SAMS)",               "Fabricante": "SABRITAS",      "Ocasión": "REUNIÓN",       "Precio ($)": 64.0,  "Gramaje (g)": 255, "SOM (%)": 0.0},
        {"Producto": "RUFFLES 280G (SAMS)",                "Fabricante": "SABRITAS",      "Ocasión": "REUNIÓN",       "Precio ($)": 64.0,  "Gramaje (g)": 280, "SOM (%)": 0.0},
        {"Producto": "MEMBER'S MARK PAPAS 500G (SAMS)",    "Fabricante": "MEMBER'S MARK", "Ocasión": "TRANSFORMADOR", "Precio ($)": 111.5, "Gramaje (g)": 500, "SOM (%)": 0.0},
        {"Producto": "CHIPS JALAPEÑO Y FUEGO 500G (SAMS)", "Fabricante": "BARCEL",        "Ocasión": "TRANSFORMADOR", "Precio ($)": 125.0, "Gramaje (g)": 500, "SOM (%)": 0.0},
        {"Producto": "CHIPS SAL 500G (CITY)",              "Fabricante": "BARCEL",        "Ocasión": "TRANSFORMADOR", "Precio ($)": 138.0, "Gramaje (g)": 500, "SOM (%)": 0.0},
        {"Producto": "CHIPS JALAPEÑO 656G (SAMS)",         "Fabricante": "BARCEL",        "Ocasión": "TRANSFORMADOR", "Precio ($)": 155.0, "Gramaje (g)": 656, "SOM (%)": 0.0},
        {"Producto": "RUFFLES QUESO 395G (COSTCO)",        "Fabricante": "SABRITAS",      "Ocasión": "TRANSFORMADOR", "Precio ($)": 159.0, "Gramaje (g)": 395, "SOM (%)": 0.0},
        {"Producto": "RECETA CRUJIENTE 490G (COSTCO)",     "Fabricante": "SABRITAS",      "Ocasión": "TRANSFORMADOR", "Precio ($)": 179.0, "Gramaje (g)": 490, "SOM (%)": 0.0},
        {"Producto": "CHIPS SAL 800G",                     "Fabricante": "BARCEL",        "Ocasión": "TRANSFORMADOR", "Precio ($)": 195.0, "Gramaje (g)": 800, "SOM (%)": 0.0},
        {"Producto": "PAPAS FRITAS LAS NORIAS 810G (SAMS)","Fabricante": "LAS NORIAS",    "Ocasión": "TRANSFORMADOR", "Precio ($)": 204.0, "Gramaje (g)": 810, "SOM (%)": 0.0},
        {"Producto": "CHIPS 4 PACK (4*170G) 680G (COSTCO)","Fabricante": "BARCEL",        "Ocasión": "TRANSFORMADOR", "Precio ($)": 206.0, "Gramaje (g)": 680, "SOM (%)": 0.0},
    ],

    "CLUBES - MAIZ": [
        {"Producto": "RANCHERITOS 350G",  "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN",       "Precio ($)": 64.0,  "Gramaje (g)": 350, "SOM (%)": 0.0},
        {"Producto": "DORITOS (SAMS) 340G","Fabricante": "SABRITAS", "Ocasión": "REUNIÓN",       "Precio ($)": 64.0,  "Gramaje (g)": 340, "SOM (%)": 0.0},
        {"Producto": "TOSTITOS 335G",     "Fabricante": "SABRITAS", "Ocasión": "REUNIÓN",       "Precio ($)": 67.0,  "Gramaje (g)": 335, "SOM (%)": 0.0},
        {"Producto": "TAKIS FUEGO 500G",  "Fabricante": "BARCEL",   "Ocasión": "TRANSFORMADOR", "Precio ($)": 110.0, "Gramaje (g)": 500, "SOM (%)": 0.0},
        {"Producto": "TAKIS FUEGO 700G",  "Fabricante": "BARCEL",   "Ocasión": "TRANSFORMADOR", "Precio ($)": 130.0, "Gramaje (g)": 700, "SOM (%)": 0.0},
        {"Producto": "DORITOS 850G",      "Fabricante": "SABRITAS", "Ocasión": "TRANSFORMADOR", "Precio ($)": 159.0, "Gramaje (g)": 850, "SOM (%)": 0.0},
    ],

}
